### ISSUE TITLE
About Fig.4 (a) Entropy

### ISSUE THREAD

**Issue by SuleBai** [mc-lan/ClearCLIP#1]
Hi, thanks for your great work!

I am interested in the `Fig.4 (a) Entropy` in the paper, but I cannot reproduce the results using the code below. I am confused about the implementation of the normalized entropy calculation.

```
def compute_normalized_entropy(tensor):
    flat_array = tensor.numpy().flatten()
    hist, _ = np.histogram(flat_array, bins=100, density=True)
    max_entropy = np.log2(len(hist))
    norm_entropy = entropy(hist, base=2) / max_entropy
    return norm_entropy
```

Could you please share the code used for plotting this figure, specifically the code for calculating the normalized entropy?

**Comment by mc-lan** [comment]
Hi Sule, thanks for your interest in our work! We have added the [calculate_normalized_entropy](https://github.com/mc-lan/ClearCLIP/blob/main/utils.py#L35) function to utils.py.

**Comment by SuleBai** [comment]
Thanks for your reply!

Besides, another question is about the Fig. 2(norm), do you calculate the norm using the code below?

```
def compute_frobenius_norm(tensor):
    # tensor: [B, L, C]
    frobenius_norm = torch.norm(tensor, p='fro')
    return frobenius_norm.item()
```

**Comment by mc-lan** [comment]
Yes, please note that B here should be 1.

**Comment by SuleBai** [comment]
Thanks a lot! Appreciate your great work!

**Comment by wokaikaixinxin** [comment]
家人们，一定要注意，在计算Entropy时，数值精度要设为double()！！否则算出来一直是NaN！！！！
