### ISSUE TITLE
About reproducing Clip result 

### ISSUE THREAD

**Issue by vanmeruso** [mc-lan/ClearCLIP#2]
Hello, thanks for your great work!

I have a question about vanilla clip result on PascalVOC20 (with background)
In paper, result show miou 16.2.
However, my reproduced result show 10.2 miou with under configuration.

Could you please share the experiment setting for vanila Clip result on PascalVOC20 with background?

# base configurations
model = dict(
    type='ClearCLIPSegmentation',
    clip_type='CLIP',     # 'CLIP', 'BLIP', 'OpenCLIP', 'MetaCLIP', 'ALIP'
    vit_type= 'ViT-B/16',      # 'ViT-B/16', 'ViT-L-14'
    model_type='vanilla',   # 'vanilla', 'MaskCLIP', 'GEM', 'SCLIP', 'ClearCLIP'
    ignore_residual=False,
)

**Comment by mc-lan** [comment]
For the experiments on the datasets with background, you may additionally need to adjust the parameter [_prob_thd_](https://github.com/mc-lan/ClearCLIP/blob/main/clearclip_segmentor.py#L109). For CLIP, we set _prob_thd=0.2_ .

**Comment by vanmeruso** [comment]
Thank for your quickly apply!

Reproduced results okay!
