### ISSUE TITLE
How to decide mean and std for segmentation?

### ISSUE THREAD

**Issue by lezhang7** [mc-lan/ClearCLIP#4]
Hi,

Thanks for your wonderful work! I have question about the `mean` and `std` used in  `class ClearCLIPSegmentation(BaseSegmentor):`

```
   data_preprocessor = SegDataPreProcessor(
    mean=[122.771, 116.746, 104.094],
    std=[68.501, 66.632, 70.323],
    bgr_to_rgb=True)
```

It's quiet different from what was used in CLIP image processor:

```
Compose(
    Resize(size=224, interpolation=bicubic, max_size=None, antialias=True)
    CenterCrop(size=(224, 224))
    <function _convert_to_rgb at 0x7f087a28a550>
    ToTensor()
    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))
)
```

 would there be a problem in this?

**Comment by mc-lan** [comment]
The mean and std values ([122.771, 116.746, 104.094] and [68.501, 66.632, 70.323]) correspond to pixel values in the 0-255 range, typically used for RGB images, while ([0.48145466, 0.4578275, 0.40821073] and [0.26862954, 0.26130258, 0.27577711]) are for normalized 0-1 pixel values. Both serve the same purpose, just applied to different pixel scales.

**Comment by lezhang7** [comment]
Thanks for your explanation!
