### ISSUE TITLE
可视化问题

### ISSUE THREAD

**Issue by xxxxxxxxxxxxxxxxxxx20gex** [mc-lan/ClearCLIP#5]
您好，在读了您的论文之后发现很多图做的非常好，可以分享一下可视化代码吗

**Comment by mc-lan** [comment]
具体你需要哪些图的代码呢

**Comment by lhqxcc** [comment]
您好，请问可以提供一下论文中图1（left）的可视化代码吗？您是使用全局文本特征和每个图像patch特征做的注意力计算吗？

**Comment by xxxxxxxxxxxxxxxxxxx20gex** [comment]
> 具体你需要哪些图的代码呢

您好，非常感谢您的回复，需要注意力的绘图，图1中左图部分

**Comment by mc-lan** [comment]
fig1 (left) 实际上是最终的分割结果比较，可以用[_trigger_visualization_hook_](https://github.com/mc-lan/ClearCLIP/blob/eddf52bf60b11eef7b376acbe34b249e368ac0e6/eval.py#L63)来可视化各个算法的最终结果。
