### ISSUE TITLE
Time for trigger_visualization_hook func excuation.

### ISSUE THREAD

**Issue by Zhiyuan-R** [mc-lan/ClearCLIP#7]
Dear Authors,

Thanks first for this awesome work! I am kindly wondering what the approximate excuation time for the trigger_visualization_hook() running. I have been stucking in this function for two hours when running eval.py file on VOC dataset.

Please let me know if you can help me. Thanks a lot!

**Comment by mc-lan** [comment]
It won't take too much time, there may be other bugs. 
In `base_config`, please set`visualization=dict(type='SegVisualizationHook', interval=10))` to see if it will improve the process more quickly.

**Comment by Zhiyuan-R** [comment]
solved! 牛逼！

**Comment by mc-lan** [comment]
lol
